<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="1" ignored="0" total="6" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="34204" started-at="2019-03-22T05:11:26Z" finished-at="2019-03-22T05:12:01Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="34204" started-at="2019-03-22T05:11:26Z" finished-at="2019-03-22T05:12:01Z">
      <class name="SalesforceApp">
        <test-method status="PASS" signature="befSuite()[pri:0, instance:SalesforceApp@9629756]" name="befSuite" is-config="true" duration-ms="26015" started-at="2019-03-21T22:11:00Z" finished-at="2019-03-21T22:11:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- befSuite -->
        <test-method status="PASS" signature="befClass()[pri:0, instance:SalesforceApp@9629756]" name="befClass" is-config="true" duration-ms="10722" started-at="2019-03-21T22:11:26Z" finished-at="2019-03-21T22:11:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- befClass -->
        <test-method status="PASS" signature="loginTest()[pri:1, instance:SalesforceApp@9629756]" name="loginTest" duration-ms="6391" started-at="2019-03-21T22:11:38Z" finished-at="2019-03-21T22:11:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="logIn()[pri:2, instance:SalesforceApp@9629756]" name="logIn" duration-ms="13665" started-at="2019-03-21T22:11:45Z" depends-on-methods="SalesforceApp.loginTest" finished-at="2019-03-21T22:11:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logIn -->
        <test-method status="FAIL" signature="closeDialogue()[pri:3, instance:SalesforceApp@9629756]" name="closeDialogue" duration-ms="1559" started-at="2019-03-21T22:11:59Z" depends-on-methods="SalesforceApp.logIn" finished-at="2019-03-21T22:12:00Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at MainClass.click(MainClass.java:117)
	at SalesforceApp.closeDialogue(SalesforceApp.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDialogue -->
        <test-method status="SKIP" signature="clickUsrNavButton()[pri:4, instance:SalesforceApp@9629756]" name="clickUsrNavButton" duration-ms="0" started-at="2019-03-21T22:12:01Z" depends-on-methods="SalesforceApp.closeDialogue" finished-at="2019-03-21T22:12:01Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SalesforceApp.clickUsrNavButton()[pri:4, instance:SalesforceApp@9629756] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SalesforceApp.clickUsrNavButton()[pri:4, instance:SalesforceApp@9629756] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clickUsrNavButton -->
        <test-method status="SKIP" signature="profileSettings()[pri:5, instance:SalesforceApp@9629756]" name="profileSettings" duration-ms="0" started-at="2019-03-21T22:12:01Z" depends-on-methods="SalesforceApp.clickUsrNavButton" finished-at="2019-03-21T22:12:01Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SalesforceApp.profileSettings()[pri:5, instance:SalesforceApp@9629756] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SalesforceApp.profileSettings()[pri:5, instance:SalesforceApp@9629756] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- profileSettings -->
        <test-method status="SKIP" signature="logOutFrmApp()[pri:0, instance:SalesforceApp@9629756]" name="logOutFrmApp" duration-ms="0" started-at="2019-03-21T22:12:01Z" depends-on-methods="SalesforceApp.profileSettings" finished-at="2019-03-21T22:12:01Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SalesforceApp.logOutFrmApp()[pri:0, instance:SalesforceApp@9629756] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SalesforceApp.logOutFrmApp()[pri:0, instance:SalesforceApp@9629756] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logOutFrmApp -->
      </class> <!-- SalesforceApp -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
